### ISSUE TITLE
gcc linter with mbed rtos.h, EthernetInterface.h

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio-atom-ide#24]
I have project with a mbed seeeduino ArchPro. I included some headerfiles like rtos.h etc.
The project works with no problem but the gcc linter gives me always a warning. It seems that the linter can't find the path. The header files are no user libs, they are syslibs of mbed.

![gcc rtos error](https://cloud.githubusercontent.com/assets/6450325/12654262/722c5a66-c5f3-11e5-92a1-caee6d484b4f.png)

**Comment by ivankravets** [comment]
Try `Menu: PlatformIO > Upgrade PlatformIO` then `Menu: PlatformIO > Initialize New Project...`. Looks like I fixed it in the latest PlatformIO development build

**Comment by sstaub** [comment]
When I try to Upgrade I get following error message:
![update_error](https://cloud.githubusercontent.com/assets/6450325/12654581/f5f931c4-c5f4-11e5-874f-f3354502bd9c.png)

**Comment by ivankravets** [comment]
See https://github.com/platformio/platformio-atom-ide/issues/23#issuecomment-176328497

**Comment by sstaub** [comment]
Works, thank you.

**Comment by ivankravets** [comment]
May I close this issue?

**Comment by ivankravets** [comment]
The linter flags are located in `.gcc-flags.json` file.

**Comment by sstaub** [comment]
Yes, you can close it.

**Comment by ivankravets** [comment]
All these problems are fixed in PlatformIO 2.8.0 which will be released today :) 
And.... The big surprise should be new PlatformIO IDE 0.3.0 (stable release with new features) :blush:  Please follow us on Twitter https://twitter.com/PlatformIO_Org


P.S: Please give us a stars :star:  for our projects:
* https://github.com/platformio/platformio/stargazers
* https://github.com/platformio/platformio-atom-ide

Thanks!
