### ISSUE TITLE
InstallationManager: ImportError: No module named functools

### ISSUE THREAD

**Issue by akkord64** [platformio/platformio-atom-ide#337]
Virtualenv Download: Traceback (most recent call last):
  File "C:/Users/Chris/.platformio/penv/lib/python2.7/site.py", line 703, in <module>
    main()
  File "C:/Users/Chris/.platformio/penv/lib/python2.7/site.py", line 692, in main
    aliasmbcs()
  File "C:/Users/Chris/.platformio/penv/lib/python2.7/site.py", line 515, in aliasmbcs
    import locale, codecs
  File "C:\Users\Chris\.platformio\penv\lib\python2.7/locale.py", line 17, in <module>
    import functools
ImportError: No module named functools

**Comment by ivankravets** [comment]
Could you run in system terminal `python --version`?

**Comment by akkord64** [comment]
C:\Users\Chris>python --version
Python 3.6.1

C:\Users\Chris>

**Comment by ivankravets** [comment]
@orgkhnargh Please remove all Pythons from your virtual machine, then install Python 3.6 and try to install PIO IDE. Clean uninstallation:

- http://docs.platformio.org/en/latest/ide/atom.html#uninstall-atom-with-platformio-ide

**Comment by stefan-schindler** [comment]
@ivankravets I'm not 100% sure, but I think Python 3 has nothing to do with it. I suppose the problem lies in the existing Python 2.7 installation. In some cases it isn't able to properly run the `virtualenv.py` setup script.

**Comment by nevercast** [comment]
This issue is not fixed. I am using Platform.IO IDE installed from APM _today_ and this is still an issue.

For my case, making `python` point to `python2` instead of `python3` fixed it. 
If you want Python 2.7, I encourage that Platform.IO checks the environment for the presence of `python2` first. That is the correct naming convention for multi-version python systems.
